baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.ruanbrandao.com.br" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging
  - jekyll-compress-images

paginate: 5
paginate_path: "/page/:num"

compress_images:
  images_path: "images/**/*.{gif,png,jpg,jpeg,svg}"

imageoptim:
  allow_lossy: true
  jpegrecompress:
    allow_lossy: true
    quality: 2
  jpegoptim:
    allow_lossy: true
    max_quality: 80
  svgo: false

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages


# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
