# Site settings
title: Blog do Ruan
email: ruan.bernardo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Introvertido sociável, desenvolvedor de software e sommelier de
  tweets.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.ruanbrandao.com.br" # the base hostname & protocol for your site
twitter_username: RuanBrandao
github_username:  ruan-brandao

# Build settings
markdown: kramdown
