# Site settings
title: Ruan Brandão
email: ruan.bernardo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Desenvolvedor Jr de São Paulo, entusiasta de tecnologias em geral, baterista
  e fã de Douglas Adams. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.ruanbrandao.com.br" # the base hostname & protocol for your site
twitter_username: RuanBrandao
github_username:  ruan-brandao

# Build settings
markdown: kramdown
