#-------------------------------
# General Site Settings
title: Ruan Brandão
logo: logo.svg # You can add own logo.
description: Site pessoal de Ruan Brandão


#-------------------------------
# Author Settings
author:
  name: Ruan Brandão
  image: eu.jpg
  image-description: Foto de Ruan Brandão
  say-hello: Olá, eu sou o <strong>Ruan Brandão</strong>
  bio: Introvertido sociável interessado em desenvolver software de qualidade e discutir como os softwares que desenvolvemos impactam o mundo ao nosso redor.
  bio-en: Full Stack Developer from São Paulo, Brazil, Ruan is a sociable introvert keen to develop great software and discuss how the various software we produce impact the world around us. He’s a gamer, an amateur musician and a curator of humorous tweets.


#-------------------------------
# Contact links
twitter: https://twitter.com/RuanBrandao
github: https://github.com/ruan-brandao


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: ruanbrandao # add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Google Analytics
google-analytics: UA-66709794-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
